version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: vit_web
    ports:
    - "8000:80"
#    volumes:
#    - "./:/var/www/vit/"
    links:
    - "mysql"
    depends_on:
    - phpmyadmin
    working_dir: /var/www/vit
  mysql:
    image: mysql:5.7
    container_name: vit_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "root"
      MYSQL_DATABASE: "vit"
    ports:
    - "3317:3306"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      PMA_HOST: "mysql"
    ports:
    - "8003:80"
    links:
    - "mysql"
